### ISSUE TITLE
Fails when _memoryName has a length > 30

### ISSUE THREAD

**Issue by JonasGessner** [DeskConnect/WFNotificationCenter#1]
If `_memoryName` is longer than 30 characters the `shm_open` call fails with the error "File name too long". It's pretty easy to get over 30 characters with the `/wfdnc` suffix.

A possible solution would be creating a short hash (32 bits, such as crc32 available in zlib) of the group identifier, appending `/wfdnc` and using that as memory name.

**Comment by conradev** [comment]
Unfortunately, this is a restriction [imposed by the OS](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW24):

> The maximum length of a POSIX semaphore name is only 31 bytes, so if you need to use POSIX semaphores, you should keep your app group names **short**.

Not only does the combined name to have a maximum length of 30, but it also has to begin with the app group identifier (per sandbox restrictions). I want to move from named semaphores to a file lock (so that it's released automatically during a crash), but I like the idea of shared memory.

Maybe switching to a regular file would be work better because of this restriction.

**Comment by JonasGessner** [comment]
I thought about the sandbox restriction too, but at least on the simulator the notification center works even with a random name (communicating from an app to an extension). Might be different on an actual device, I haven't tested that yet!

For now I'll just shorten my app group name, but it isn't easy considering it even has to be prefixed by `group.` :P 

Is there any particular reason why this isn't production ready yet, besides the naming restriction? This is the only `NSNotificationCenter` style communication project for app groups I could find.

**Comment by conradev** [comment]
Yeah, the simulator has no restrictions, you can make mach ports and semaphores with any name.

The main reason is because things aren't final, I need to go in and finalize them (add `observer` support, use secure coding, etc.), and add tests. The only current bug is that if the code crashes when modifying the ports registry, which has happened, the semaphore remains locked up, which is a nasty issue to have happen. I want to a) make sure the crash doesn't happen and b) make sure that if the crash does happen, the notification center isn't locked up.

**Comment by JonasGessner** [comment]
OK, I'm not familiar with CFMessagePort but I could try and help fixing the ports registry bug! I'm using the notification center in pre-production code right now and it's brilliant, so I really want this to be production ready when I release the app I'm working on ;)

**Comment by conradev** [comment]
I think the code is now at a point where I am comfortable using it in production :)

**Comment by JonasGessner** [comment]
Absolutely boss, thank you so much! :) Great project!
